const router = require('express').Router();
const ctrl = require('../controllers/RideController');
const { authenticate, authorize } = require('../middleware/auth');
router.use(authenticate);
router.post('/estimate', ctrl.getFareEstimate);
router.post('/book', ctrl.bookRide);
router.get('/active', ctrl.getActiveRide);
router.get('/history', ctrl.getRideHistory);
router.get('/searching/available', authorize('driver'), ctrl.getSearchingRides);
router.get('/:id', ctrl.getRideDetails);
router.post('/:id/cancel', ctrl.cancelRide);
router.post('/:id/rate', ctrl.rateRide);
module.exports = router;
